export { StatusTiles, type StatusTilesProps } from './StatusTiles';
export {
  DEFAULT_STRIP_HEIGHT,
  DEFAULT_STRIP_WIDTH,
  DOCK_HOVER_WIDTH,
  DOCK_PADDING,
  layoutTabs,
  MAX_VISIBLE_TABS,
  minimumHeightForSlots,
  normalizeStripWidth,
  revealedTabWidth,
  sessionHitRegions,
  stackHeight,
  TAB_GAP,
  TAB_HEIGHT,
  TAB_HIT_MIN_WIDTH,
  TAB_ICON_GAP,
  TAB_ICON_SIZE,
  TAB_LABEL_MAX_WIDTH,
  TAB_MOTION_MS,
  TAB_PADDING_END,
  TAB_PADDING_START,
  TAB_PEEK_DOCK,
  TAB_PEEK_IDLE,
  TAB_RADIUS,
  TAB_STAGGER_MS,
  tabHitRegion,
  visibleSlotCount,
  type TabLayout,
  type TabLayoutOptions,
  type TabSlot,
  type TileHitRegion,
} from './geometry';
export {
  canAcknowledgeTarget,
  captureOpenTarget,
  isSameSessionOrder,
  updateFrozenSessionStatuses,
  visibleTileSessions,
  type OpenSessionTarget,
} from './interaction';
export { TILE_COLORS, STATUS_COLOR, statusLabel } from './theme';
